# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=['C:\CyberBall'],
    binaries=[],
    datas=[('data/ball.png', 'data'), 
            ('data/big_choice_frame.png', 'data'),
            ('data/big_green_frame.png', 'data'),
            ('data/big_red_frame.png', 'data'),
            ('data/blue_tile.png', 'data'),
            ('data/choice_frame.png', 'data'),
            ('data/click.png', 'data'),
            ('data/DB.db', 'data'),
            ('data/game_over.png', 'data'),
            ('data/green_frame.png', 'data'),
            ('data/green_tile.png', 'data'),
            ('data/level.png', 'data'),
            ('data/level1.txt', 'data'),
            ('data/level2.txt', 'data'),
            ('data/level3.txt', 'data'),
            ('data/lives.png', 'data'),
            ('data/menu.png', 'data'),
            ('data/mini_quit.png', 'data'),
            ('data/orange_tile.png', 'data'),
            ('data/panel4.png', 'data'),
            ('data/panel8.png', 'data'),
            ('data/panel16.png', 'data'),
            ('data/Pixon.ttf', 'data'),
            ('data/planet.png', 'data'),
            ('data/play.png', 'data'),
            ('data/pointer.png', 'data'),
            ('data/purple_tile.png', 'data'),
            ('data/quit.png', 'data'),
            ('data/red_frame.png', 'data'),
            ('data/red_tile.png', 'data'),
            ('data/score.png', 'data'),
            ('data/sphere1.png', 'data'),
            ('data/sphere2.png', 'data'),
            ('data/sphere3.png', 'data'),
            ('data/sphere4.png', 'data'),
            ('data/sphere5.png', 'data'),
            ('data/sphere6.png', 'data'),
            ('data/sphere7.png', 'data'),
            ('data/sphere8.png', 'data'),
            ('data/sphere9.png', 'data'),
            ('data/sphere10.png', 'data'),
            ('data/sphere11.png', 'data'),
            ('data/sphere12.png', 'data'),
            ('data/sphere13.png', 'data'),
            ('data/sphere14.png', 'data'),
            ('data/sphere15.png', 'data'),
            ('data/sphere16.png', 'data'),
            ('data/sphere17.png', 'data'),
            ('data/sphere18.png', 'data'),
            ('data/sphere19.png', 'data'),
            ('data/sphere20.png', 'data'),
            ('data/sphere21.png', 'data'),
            ('data/sphere22.png', 'data'),
            ('data/sphere23.png', 'data'),
            ('data/sphere24.png', 'data'),
            ('data/stars.png', 'data'),
            ('data/title.png', 'data'),
            ('data/turquoise_tile.png', 'data'),
            ('data/yellow_tile.png', 'data'),
            ('data/icon.ico', 'data'),
            ('data/icon.png', 'data'),
            ('sound_effects/brick_hit.wav', 'sound_effects'),
            ('sound_effects/effect_done.wav', 'sound_effects'),
            ('sound_effects/game_over.wav', 'sound_effects'),
            ('sound_effects/live.wav', 'sound_effects'),
            ('sound_effects/music.mp3', 'sound_effects'),
            ('sound_effects/paddle_hit.wav', 'sound_effects'),
            ('sound_effects/win.wav', 'sound_effects')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CyberBall',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='C:\CyberBall\data\icon.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
